In [5]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/walmart-recruiting-store-sales-forecasting/train.csv.zip
/kaggle/input/walmart-recruiting-store-sales-forecasting/sampleSubmission.csv.zip
/kaggle/input/walmart-recruiting-store-sales-forecasting/stores.csv
/kaggle/input/walmart-recruiting-store-sales-forecasting/features.csv.zip
/kaggle/input/walmart-recruiting-store-sales-forecasting/test.csv.zip

In [1]:
!pip install dagshub mlflow --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 261.0/261.0 kB 8.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.7/24.7 MB 71.7 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 52.9 MB/s eta 0:00:00:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 2.8 MB/s eta 0:00:000:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.0/85.0 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 733.8/733.8 kB 35.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.6/95.6 kB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.4/203.4 kB 12.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.3/74.3 kB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 4.8 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ydata-profiling 4.16.1 requires dacite>=1.8, but you have dacite 1.6.0 which is incompatible.
cesium 0.12.4 requires numpy<3.0,>=2.0, but you have numpy 1.26.4 which is incompatible.

In [6]:
# import dagshub 
# import mlflow
# dagshub.init(repo_owner='gkuch22', repo_name='ml-final', mlflow=True)

                                       ❗❗❗ AUTHORIZATION REQUIRED ❗❗❗

Open the following link in your browser to authorize the client:
https://dagshub.com/login/oauth/authorize?state=b10d03dc-bb75-4ccc-b72e-0003292843b1&client_id=32b60ba385aa7cecf24046d8195a71c07dd345d9657977863b52e7748e0f0f28&middleman_request_id=8d47eee065f8f5fec81df439b104b02d30521002769c68af8d71787e4ddff9f5

Output()

Accessing as Luka-Surmanidze

Initialized MLflow to track repo "gkuch22/ml-final"

Repository gkuch22/ml-final initialized!

In [111]:
train_csv = pd.read_csv('/kaggle/input/walmart-recruiting-store-sales-forecasting/train.csv.zip')

In [112]:
train_csv.head(200)

     Store  Dept        Date  Weekly_Sales  IsHoliday
0        1     1  2010-02-05      24924.50      False
1        1     1  2010-02-12      46039.49       True
2        1     1  2010-02-19      41595.55      False
3        1     1  2010-02-26      19403.54      False
4        1     1  2010-03-05      21827.90      False
..     ...   ...         ...           ...        ...
195      1     2  2011-02-04      46829.12      False
196      1     2  2011-02-11      47595.35       True
197      1     2  2011-02-18      49202.06      False
198      1     2  2011-02-25      46165.25      False
199      1     2  2011-03-04      53035.54      False

[200 rows x 5 columns]

In [113]:
stores = pd.read_csv('/kaggle/input/walmart-recruiting-store-sales-forecasting/stores.csv')

In [114]:
stores.head(46)

    Store Type    Size
0       1    A  151315
1       2    A  202307
2       3    B   37392
3       4    A  205863
4       5    B   34875
5       6    A  202505
6       7    B   70713
7       8    A  155078
8       9    B  125833
9      10    B  126512
10     11    A  207499
11     12    B  112238
12     13    A  219622
13     14    A  200898
14     15    B  123737
15     16    B   57197
16     17    B   93188
17     18    B  120653
18     19    A  203819
19     20    A  203742
20     21    B  140167
21     22    B  119557
22     23    B  114533
23     24    A  203819
24     25    B  128107
25     26    A  152513
26     27    A  204184
27     28    A  206302
28     29    B   93638
29     30    C   42988
30     31    A  203750
31     32    A  203007
32     33    A   39690
33     34    A  158114
34     35    B  103681
35     36    A   39910
36     37    C   39910
37     38    C   39690
38     39    A  184109
39     40    A  155083
40     41    A  196321
41     42    C   39690
42     43    C   41062
43     44    C   39910
44     45    B  118221

In [115]:
features = pd.read_csv('/kaggle/input/walmart-recruiting-store-sales-forecasting/features.csv.zip')

In [116]:
import pandas as pd
import numpy as np
import lightgbm as lgb
from sklearn.metrics import mean_absolute_error


train = pd.read_csv("/kaggle/input/walmart-recruiting-store-sales-forecasting/train.csv.zip", parse_dates=["Date"])
features = pd.read_csv("/kaggle/input/walmart-recruiting-store-sales-forecasting/features.csv.zip", parse_dates=["Date"])
stores = pd.read_csv("/kaggle/input/walmart-recruiting-store-sales-forecasting/stores.csv")

In [117]:
full = train.merge(features, on=["Store", "Date"], how="left")
full = full.merge(stores, on="Store", how="left")

In [7]:
# experiment_name = "LightGBM"
# mlflow.set_experiment(experiment_name)

<Experiment: artifact_location='mlflow-artifacts:/77ee129a12b740c9ab5e1c80d7a443a6', creation_time=1751529211039, experiment_id='4', last_update_time=1751529211039, lifecycle_stage='active', name='LightGBM', tags={}>

In [119]:
mlflow.end_run()

In [120]:

# # mlflow.end_run()
# mlflow.start_run(run_name="LightGBM_CleaningV1")

# mlflow.log_param("Part", "Cleaning")
# mlflow.log_param("Na columns Only Markdowns", "Filled with zeros")

# mlflow.end_run()

In [121]:
markdown_cols = ["MarkDown1", "MarkDown2", "MarkDown3", "MarkDown4", "MarkDown5"]
for col in markdown_cols:
    if col in full.columns:
        full[col] = full[col].fillna(0)

In [122]:
full.isna().mean()

Store           0.0
Dept            0.0
Date            0.0
Weekly_Sales    0.0
IsHoliday_x     0.0
Temperature     0.0
Fuel_Price      0.0
MarkDown1       0.0
MarkDown2       0.0
MarkDown3       0.0
MarkDown4       0.0
MarkDown5       0.0
CPI             0.0
Unemployment    0.0
IsHoliday_y     0.0
Type            0.0
Size            0.0
dtype: float64

In [123]:
full["Type"] = full["Type"].astype("category")

In [124]:
full

,Store,Dept,Date,Weekly_Sales,IsHoliday_x,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday_y,Type,Size
0,1,1,2010-02-05,24924.50,False,42.31,2.572,0.00,0.00,0.00,0.00,0.00,211.096358,8.106,False,A,151315
1,1,1,2010-02-12,46039.49,True,38.51,2.548,0.00,0.00,0.00,0.00,0.00,211.242170,8.106,True,A,151315
2,1,1,2010-02-19,41595.55,False,39.93,2.514,0.00,0.00,0.00,0.00,0.00,211.289143,8.106,False,A,151315
3,1,1,2010-02-26,19403.54,False,46.63,2.561,0.00,0.00,0.00,0.00,0.00,211.319643,8.106,False,A,151315
4,1,1,2010-03-05,21827.90,False,46.50,2.625,0.00,0.00,0.00,0.00,0.00,211.350143,8.106,False,A,151315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421565,45,98,2012-09-28,508.37,False,64.88,3.997,4556.61,20.64,1.50,1601.01,3288.25,192.013558,8.684,False,B,118221
421566,45,98,2012-10-05,628.10,False,64.89,3.985,5046.74,0.00,18.82,2253.43,2340.01,192.170412,8.667,False,B,118221
421567,45,98,2012-10-12,1061.02,False,54.47,4.000,1956.28,0.00,7.89,599.32,3990.54,192.327265,8.667,False,B,118221
421568,45,98,2012-10-19,760.01,False,56.47,3.969,2004.02,0.00,3.18,437.73,1537.49,192.330854,8.667,False,B,118221
421569,45,98,2012-10-26,1076.80,False,58.85,3.882,4018.91,58.08,100.00,211.94,858.33,192.308899,8.667,False,B,118221

In [125]:
full = full.sort_values(by=["Store", "Dept", "Date"]).reset_index(drop=True)

In [126]:
full

,Store,Dept,Date,Weekly_Sales,IsHoliday_x,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday_y,Type,Size
0,1,1,2010-02-05,24924.50,False,42.31,2.572,0.00,0.00,0.00,0.00,0.00,211.096358,8.106,False,A,151315
1,1,1,2010-02-12,46039.49,True,38.51,2.548,0.00,0.00,0.00,0.00,0.00,211.242170,8.106,True,A,151315
2,1,1,2010-02-19,41595.55,False,39.93,2.514,0.00,0.00,0.00,0.00,0.00,211.289143,8.106,False,A,151315
3,1,1,2010-02-26,19403.54,False,46.63,2.561,0.00,0.00,0.00,0.00,0.00,211.319643,8.106,False,A,151315
4,1,1,2010-03-05,21827.90,False,46.50,2.625,0.00,0.00,0.00,0.00,0.00,211.350143,8.106,False,A,151315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421565,45,98,2012-09-28,508.37,False,64.88,3.997,4556.61,20.64,1.50,1601.01,3288.25,192.013558,8.684,False,B,118221
421566,45,98,2012-10-05,628.10,False,64.89,3.985,5046.74,0.00,18.82,2253.43,2340.01,192.170412,8.667,False,B,118221
421567,45,98,2012-10-12,1061.02,False,54.47,4.000,1956.28,0.00,7.89,599.32,3990.54,192.327265,8.667,False,B,118221
421568,45,98,2012-10-19,760.01,False,56.47,3.969,2004.02,0.00,3.18,437.73,1537.49,192.330854,8.667,False,B,118221
421569,45,98,2012-10-26,1076.80,False,58.85,3.882,4018.91,58.08,100.00,211.94,858.33,192.308899,8.667,False,B,118221

In [127]:
full["year"] = full["Date"].dt.year
full["month"] = full["Date"].dt.month
full["week"] = full["Date"].dt.isocalendar().week.astype(int)
full["dayofweek"] = full["Date"].dt.dayofweek
full["is_weekend"] = full["dayofweek"] >= 5

In [128]:
full.isna().mean()

Store           0.0
Dept            0.0
Date            0.0
Weekly_Sales    0.0
IsHoliday_x     0.0
Temperature     0.0
Fuel_Price      0.0
MarkDown1       0.0
MarkDown2       0.0
MarkDown3       0.0
MarkDown4       0.0
MarkDown5       0.0
CPI             0.0
Unemployment    0.0
IsHoliday_y     0.0
Type            0.0
Size            0.0
year            0.0
month           0.0
week            0.0
dayofweek       0.0
is_weekend      0.0
dtype: float64

In [129]:
def create_lag_features(data, lags=[1, 52]):
    for lag in lags:
        data[f"lag_{lag}"] = data.groupby(["Store", "Dept"])["Weekly_Sales"].shift(lag)
    return data

In [130]:
def create_rolling_features(data, windows=[3]):
    for window in windows:
        data[f"rolling_mean_{window}"] = (
            data.groupby(["Store", "Dept"])["Weekly_Sales"]
            .shift(1)
            .rolling(window)
            .mean()
        )
    return data

In [131]:
full = create_lag_features(full)
full = create_rolling_features(full)

full = full.dropna()

In [132]:
full.isna().mean()

Store             0.0
Dept              0.0
Date              0.0
Weekly_Sales      0.0
IsHoliday_x       0.0
Temperature       0.0
Fuel_Price        0.0
MarkDown1         0.0
MarkDown2         0.0
MarkDown3         0.0
MarkDown4         0.0
MarkDown5         0.0
CPI               0.0
Unemployment      0.0
IsHoliday_y       0.0
Type              0.0
Size              0.0
year              0.0
month             0.0
week              0.0
dayofweek         0.0
is_weekend        0.0
lag_1             0.0
lag_52            0.0
rolling_mean_3    0.0
dtype: float64

In [133]:
train_df = full[full["Date"] <= "2012-05-31"]
valid_df = full[(full["Date"] > "2012-05-31") & (full["Date"] <= "2012-08-31")]
test_df = full[(full["Date"] > "2012-08-31")]

print("Train rows:", len(train_df))
print("Valid rows:", len(valid_df))
print("Test rows:", len(test_df))

Train rows: 197201
Valid rows: 40516
Test rows: 23366

In [134]:
train_df.head()

,Store,Dept,Date,Weekly_Sales,IsHoliday_x,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,...,Type,Size,year,month,week,dayofweek,is_weekend,lag_1,lag_52,rolling_mean_3
52,1,1,2011-02-04,21665.76,False,42.27,2.989,0.0,0.0,0.0,...,A,151315,2011,2,5,4,False,18461.18,24924.50,17720.783333
53,1,1,2011-02-11,37887.17,True,36.39,3.022,0.0,0.0,0.0,...,A,151315,2011,2,6,4,False,21665.76,46039.49,19156.136667
54,1,1,2011-02-18,46845.87,False,57.36,3.045,0.0,0.0,0.0,...,A,151315,2011,2,7,4,False,37887.17,41595.55,26004.703333
55,1,1,2011-02-25,19363.83,False,62.90,3.065,0.0,0.0,0.0,...,A,151315,2011,2,8,4,False,46845.87,19403.54,35466.266667
56,1,1,2011-03-04,20327.61,False,59.58,3.288,0.0,0.0,0.0,...,A,151315,2011,3,9,4,False,19363.83,21827.90,34698.956667

In [140]:
target = "Weekly_Sales"
categorical = ["Store", "Dept", "Type", "IsHoliday_x"]
features = [
    "Store", "Dept", "Type", "IsHoliday_x", "Size", "Temperature", "Fuel_Price",
    "CPI", "Unemployment", "year", "month", "week", "dayofweek", "is_weekend",
    "lag_1", "lag_52", "rolling_mean_3"
]

lgb_train = lgb.Dataset(train_df[features], train_df[target], categorical_feature=categorical, free_raw_data=False)
lgb_valid = lgb.Dataset(valid_df[features], valid_df[target], categorical_feature=categorical, free_raw_data=False)

In [136]:
# features_added = ["year", "month", "week", "dayofweek", "isweekend", "lags", "rolling_means"]

# mlflow.start_run(run_name="LightGBM_Feature_SelectionV1")
# mlflow.log_param("Features Added", features_added)
# mlflow.log_param("selected_features", features)
# mlflow.log_metric("num_features", len(features))
# mlflow.end_run()

In [137]:
params = {
    'objective': 'regression',
    'metric': 'rmse',
    'boosting_type': 'gbdt',
    'learning_rate': 0.05,
    'num_leaves': 31,
    'feature_fraction': 0.8,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'seed': 42,
    'verbose': -1
}

In [141]:
def WMAE(y_true, y_pred, is_holiday):
    weights = np.where(is_holiday, 5, 1)
    return np.sum(weights * np.abs(y_true - y_pred)) / np.sum(weights)

In [ ]:
param_grid = {
    "learning_rate": [0.03, 0.05, 0.1],
    "num_leaves": [31, 63, 127],
    "feature_fraction": [0.8, 1.0],
    "bagging_fraction": [0.8, 1.0],
}

best_wmae = float("inf")
best_params = None

for lr in param_grid["learning_rate"]:
    for leaves in param_grid["num_leaves"]:
        for feat_frac in param_grid["feature_fraction"]:
            for bag_frac in param_grid["bagging_fraction"]:

                params = {
                    'objective': 'regression',
                    'metric': 'rmse',
                    'boosting_type': 'gbdt',
                    'learning_rate': lr,
                    'num_leaves': leaves,
                    'feature_fraction': feat_frac,
                    'bagging_fraction': bag_frac,
                    'bagging_freq': 5,
                    'seed': 42,
                    'verbose': -1
                }

                model = lgb.train(
                    params,
                    lgb_train,
                    valid_sets=[lgb_train, lgb_valid],
                    num_boost_round=2000
                )

                val_preds = model.predict(valid_df[features])
                val_score = WMAE(valid_df[target].values, val_preds, valid_df["IsHoliday_x"].values)

                print(f"lr={lr}, leaves={leaves}, feat_frac={feat_frac}, bag_frac={bag_frac} -> WMAE: {val_score:.4f}")

                if val_score < best_wmae:
                    best_wmae = val_score
                    best_params = params

print("Best WMAE:", best_wmae)
print("Best Params:", best_params)

model = lgb.train(
    best_params,
    lgb_train,
    valid_sets=[lgb_train, lgb_valid],
    num_boost_round=2000,
)

In [144]:
train_preds = model.predict(train_df[features])
val_preds = model.predict(valid_df[features])
test_preds = model.predict(test_df[features])

def WMAE(y_true, y_pred, is_holiday):
    weights = np.where(is_holiday, 5, 1)
    return np.sum(weights * np.abs(y_true - y_pred)) / np.sum(weights)

train_score = WMAE(train_df[target].values, train_preds, train_df["IsHoliday_x"].values)
val_score = WMAE(valid_df[target].values, val_preds, valid_df["IsHoliday_x"].values)
test_score = WMAE(test_df[target].values, test_preds, test_df["IsHoliday_x"].values)

print(f"Train WMAE: {train_score:.4f}")
print(f"Validation WMAE: {val_score:.4f}")
print(f"Test WMAE: {test_score:.4f}")

Train WMAE: 1102.6358
Validation WMAE: 1345.6726
Test WMAE: 1487.4516

In [153]:
mlflow.end_run()

🏃 View run LightGBM_CrossValidationV1 at: https://dagshub.com/gkuch22/ml-final.mlflow/#/experiments/4/runs/8b75bbd7aa38422483e430a55d6667b1
🧪 View experiment at: https://dagshub.com/gkuch22/ml-final.mlflow/#/experiments/4

In [156]:
pip install mlflow==2.10.2

Collecting mlflow==2.10.2
  Downloading mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.10.2) (8.1.8)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.10.2) (3.1.1)
Requirement already satisfied: entrypoints<1 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.10.2) (0.4)
Requirement already satisfied: gitpython<4,>=2.1.0 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.10.2) (3.1.44)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.10.2) (6.0.2)
Requirement already satisfied: protobuf<5,>=3.12.0 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.10.2) (3.20.3)
Collecting pytz<2024 (from mlflow==2.10.2)
  Downloading pytz-2023.4-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.10.2) (2.32.3)
Collecting packaging<24 (from mlflow==2.10.2)
  Downloading packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting importlib-metadata!=4.7.0,<8,>=3.7.0 (from mlflow==2.10.2)
  Downloading importlib_metadata-7.2.1-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.10.2) (0.5.3)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.10.2) (1.15.2)
Requirement already satisfied: docker<8,>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.10.2) (7.1.0)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.10.2) (3.1.0)
Requirement already satisfied: numpy<2 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.10.2) (1.26.4)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.10.2) (1.15.2)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.10.2) (2.2.3)
Collecting querystring-parser<2 (from mlflow==2.10.2)
  Downloading querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.10.2) (2.0.40)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.10.2) (1.2.2)
Collecting pyarrow<16,>=4.0.0 (from mlflow==2.10.2)
  Downloading pyarrow-15.0.2-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: markdown<4,>=3.3 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.10.2) (3.7)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.10.2) (3.7.2)
Collecting gunicorn<22 (from mlflow==2.10.2)
  Downloading gunicorn-21.2.0-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: Jinja2<4,>=2.11 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.10.2) (3.1.6)
Requirement already satisfied: Mako in /usr/local/lib/python3.11/dist-packages (from alembic!=1.10.0,<2->mlflow==2.10.2) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.11/dist-packages (from alembic!=1.10.0,<2->mlflow==2.10.2) (4.13.2)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.11/dist-packages (from docker<8,>=4.0.0->mlflow==2.10.2) (2.4.0)
Requirement already satisfied: Werkzeug>=3.1 in /usr/local/lib/python3.11/dist-packages (from Flask<4->mlflow==2.10.2) (3.1.3)
Requirement already satisfied: itsdangerous>=2.2 in /usr/local/lib/python3.11/dist-packages (from Flask<4->mlflow==2.10.2) (2.2.0)
Requirement already satisfied: blinker>=1.9 in /usr/local/lib/python3.11/dist-packages (from Flask<4->mlflow==2.10.2) (1.9.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2) (4.0.12)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.11/dist-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2) (3.21.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from Jinja2<4,>=2.11->mlflow==2.10.2) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4->mlflow==2.10.2) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4->mlflow==2.10.2) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4->mlflow==2.10.2) (4.57.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4->mlflow==2.10.2) (1.4.8)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4->mlflow==2.10.2) (11.1.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4->mlflow==2.10.2) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4->mlflow==2.10.2) (2.9.0.post0)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy<2->mlflow==2.10.2) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy<2->mlflow==2.10.2) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy<2->mlflow==2.10.2) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy<2->mlflow==2.10.2) (2025.1.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy<2->mlflow==2.10.2) (2022.1.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy<2->mlflow==2.10.2) (2.4.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<3->mlflow==2.10.2) (2025.2)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from querystring-parser<2->mlflow==2.10.2) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.17.3->mlflow==2.10.2) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.17.3->mlflow==2.10.2) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.17.3->mlflow==2.10.2) (2025.4.26)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from scikit-learn<2->mlflow==2.10.2) (1.5.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn<2->mlflow==2.10.2) (3.6.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2) (3.1.1)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2) (5.0.2)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy<2->mlflow==2.10.2) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy<2->mlflow==2.10.2) (2022.1.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy<2->mlflow==2.10.2) (1.3.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy<2->mlflow==2.10.2) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy<2->mlflow==2.10.2) (2024.2.0)
Downloading mlflow-2.10.2-py3-none-any.whl (19.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.5/19.5 MB 56.1 MB/s eta 0:00:00:00:0100:01
Downloading gunicorn-21.2.0-py3-none-any.whl (80 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.2/80.2 kB 4.4 MB/s eta 0:00:00
Downloading importlib_metadata-7.2.1-py3-none-any.whl (25 kB)
Downloading packaging-23.2-py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 2.6 MB/s eta 0:00:00
Downloading pyarrow-15.0.2-cp311-cp311-manylinux_2_28_x86_64.whl (38.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.3/38.3 MB 35.3 MB/s eta 0:00:00:00:0100:01
Downloading pytz-2023.4-py2.py3-none-any.whl (506 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 506.5/506.5 kB 21.5 MB/s eta 0:00:00
Downloading querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
Installing collected packages: pytz, querystring-parser, packaging, importlib-metadata, gunicorn, pyarrow, mlflow
  Attempting uninstall: pytz
    Found existing installation: pytz 2025.2
    Uninstalling pytz-2025.2:
      Successfully uninstalled pytz-2025.2
  Attempting uninstall: packaging
    Found existing installation: packaging 25.0
    Uninstalling packaging-25.0:
      Successfully uninstalled packaging-25.0
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib_metadata 8.6.1
    Uninstalling importlib_metadata-8.6.1:
      Successfully uninstalled importlib_metadata-8.6.1
  Attempting uninstall: gunicorn
    Found existing installation: gunicorn 23.0.0
    Uninstalling gunicorn-23.0.0:
      Successfully uninstalled gunicorn-23.0.0
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 19.0.1
    Uninstalling pyarrow-19.0.1:
      Successfully uninstalled pyarrow-19.0.1
  Attempting uninstall: mlflow
    Found existing installation: mlflow 3.1.1
    Uninstalling mlflow-3.1.1:
      Successfully uninstalled mlflow-3.1.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 3.6.0 requires fsspec[http]<=2025.3.0,>=2023.1.0, but you have fsspec 2025.3.2 which is incompatible.
ydata-profiling 4.16.1 requires dacite>=1.8, but you have dacite 1.6.0 which is incompatible.
cesium 0.12.4 requires numpy<3.0,>=2.0, but you have numpy 1.26.4 which is incompatible.
google-colab 1.0.0 requires google-auth==2.38.0, but you have google-auth 2.40.1 which is incompatible.
google-colab 1.0.0 requires notebook==6.5.7, but you have notebook 6.5.4 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.2.3 which is incompatible.
dopamine-rl 4.1.2 requires gymnasium>=1.0.0, but you have gymnasium 0.29.0 which is incompatible.
ibis-framework 9.5.0 requires toolz<1,>=0.11, but you have toolz 1.0.0 which is incompatible.
bigframes 1.42.0 requires rich<14,>=12.4.4, but you have rich 14.0.0 which is incompatible.
plotnine 0.14.5 requires matplotlib>=3.8.0, but you have matplotlib 3.7.2 which is incompatible.
pandas-gbq 0.28.0 requires google-api-core<3.0.0dev,>=2.10.2, but you have google-api-core 1.34.1 which is incompatible.
mlxtend 0.23.4 requires scikit-learn>=1.3.1, but you have scikit-learn 1.2.2 which is incompatible.
Successfully installed gunicorn-21.2.0 importlib-metadata-7.2.1 mlflow-2.10.2 packaging-23.2 pyarrow-15.0.2 pytz-2023.4 querystring-parser-1.2.4
Note: you may need to restart the kernel to use updated packages.

In [9]:
# mlflow.end_run()
# mlflow.start_run(run_name="LightGBM_CrossValidationV1")
# mlflow.log_params(best_params)
# mlflow.log_metric("Train_wmae", train_score)
# mlflow.log_metric("Valid_wmae", val_score)
# mlflow.log_metric("Test_wmae", test_score)
# mlflow.end_run()

🏃 View run LightGBM_CrossValidationV1 at: https://dagshub.com/gkuch22/ml-final.mlflow/#/experiments/4/runs/69ee737e8a404c4d9658859d029edddd
🧪 View experiment at: https://dagshub.com/gkuch22/ml-final.mlflow/#/experiments/4
🏃 View run LightGBM_CrossValidationV2 at: https://dagshub.com/gkuch22/ml-final.mlflow/#/experiments/4/runs/bb0df8cebdd441e49edba2bd4d84862b
🧪 View experiment at: https://dagshub.com/gkuch22/ml-final.mlflow/#/experiments/4

In [2]:
test_csv = pd.read_csv('/kaggle/input/walmart-recruiting-store-sales-forecasting/test.csv.zip')

In [4]:
test_csv.tail()

        Store  Dept        Date  IsHoliday
115059     45    98  2013-06-28      False
115060     45    98  2013-07-05      False
115061     45    98  2013-07-12      False
115062     45    98  2013-07-19      False
115063     45    98  2013-07-26      False